<?php

declare(strict_types=1);

use App\Controllers\HomeController;
use App\Controllers\AiAnalysisController;
use App\Controllers\AuthController;
use App\Controllers\AppointmentController;
use App\Controllers\AuditController;
use App\Controllers\ClinicalSessionController;
use App\Controllers\MaintainerController;
use App\Controllers\PatientConsentController;
use App\Controllers\PatientController;
use App\Controllers\PatientFamilyRelationshipController;
use App\Controllers\ProfessionalProfileController;
use App\Controllers\PsychometricController;
use App\Controllers\PsychometricInstrumentController;
use App\Controllers\ReportController;
use App\Controllers\UserController;
use Core\App;
use Core\Router;

require dirname(__DIR__) . '/bootstrap/app.php';

$router = new Router();

$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/registro', [AuthController::class, 'register']);
$router->post('/registro', [AuthController::class, 'storeRegistration']);
$router->get('/auth/google', [AuthController::class, 'googleRedirect']);
$router->get('/auth/google/callback', [AuthController::class, 'googleCallback']);
$router->get('/registro/google', [AuthController::class, 'googleRegisterRedirect']);
$router->get('/registro/google/callback', [AuthController::class, 'googleRegisterCallback']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/perfil/profesional', [ProfessionalProfileController::class, 'edit']);
$router->post('/perfil/profesional/actualizar', [ProfessionalProfileController::class, 'update']);
$router->get('/', [HomeController::class, 'index']);
$router->get('/panel', [HomeController::class, 'panel']);
$router->get('/citas', [AppointmentController::class, 'index']);
$router->get('/citas/{id}/editar', [AppointmentController::class, 'edit']);
$router->post('/citas/{id}/actualizar', [AppointmentController::class, 'update']);
$router->get('/citas/{id}', [AppointmentController::class, 'show']);
$router->get('/auditoria', [AuditController::class, 'index']);
$router->get('/instrumentos', [PsychometricInstrumentController::class, 'index']);
$router->get('/instrumentos/{id}/vista-previa', [PsychometricInstrumentController::class, 'preview']);
$router->get('/instrumentos/{id}/edit', [PsychometricInstrumentController::class, 'edit']);
$router->post('/instrumentos/{id}/actualizar', [PsychometricInstrumentController::class, 'update']);
$router->get('/instrumentos/{id}/activar', [PsychometricInstrumentController::class, 'activate']);
$router->get('/instrumentos/{id}/desactivar', [PsychometricInstrumentController::class, 'deactivate']);
$router->get('/informes', [ReportController::class, 'index']);
$router->get('/maintainers', [MaintainerController::class, 'index']);
$router->get('/maintainers/{table}/create', [MaintainerController::class, 'create']);
$router->post('/maintainers/{table}', [MaintainerController::class, 'store']);
$router->post('/maintainers/tipos-tema-sesion/{id}/subtipos', [MaintainerController::class, 'storeTopicSubtype']);
$router->post('/maintainers/tipos-tema-sesion/{id}/subtipos/{subtypeId}/quitar', [MaintainerController::class, 'deleteTopicSubtype']);
$router->get('/maintainers/tipos-tema-sesion/{id}/subtipos/{subtypeId}/publicar', [MaintainerController::class, 'publishTopicSubtype']);
$router->get('/maintainers/tipos-tema-sesion/{id}/subtipos/{subtypeId}/privatizar', [MaintainerController::class, 'privatizeTopicSubtype']);
$router->get('/maintainers/tipos-tema-sesion/{id}/subtipos/{subtypeId}/activar', [MaintainerController::class, 'activateTopicSubtype']);
$router->get('/maintainers/tipos-tema-sesion/{id}/subtipos/{subtypeId}/desactivar', [MaintainerController::class, 'deactivateTopicSubtype']);
$router->get('/maintainers/tipos-tema-sesion/{id}/publicar', [MaintainerController::class, 'publishTopicType']);
$router->get('/maintainers/tipos-tema-sesion/{id}/privatizar', [MaintainerController::class, 'privatizeTopicType']);
$router->get('/maintainers/{table}/{id}/edit', [MaintainerController::class, 'edit']);
$router->post('/maintainers/{table}/{id}/update', [MaintainerController::class, 'update']);
$router->get('/maintainers/{table}/{id}/activate', [MaintainerController::class, 'activate']);
$router->get('/maintainers/{table}/{id}/deactivate', [MaintainerController::class, 'deactivate']);
$router->get('/maintainers/{table}', [MaintainerController::class, 'table']);
$router->get('/usuarios', [UserController::class, 'index']);
$router->get('/usuarios/crear', [UserController::class, 'create']);
$router->post('/usuarios', [UserController::class, 'store']);
$router->get('/usuarios/{id}/editar', [UserController::class, 'edit']);
$router->post('/usuarios/{id}/actualizar', [UserController::class, 'update']);
$router->get('/usuarios/{id}/activar', [UserController::class, 'activate']);
$router->get('/usuarios/{id}/desactivar', [UserController::class, 'deactivate']);
$router->get('/patients', [PatientController::class, 'index']);
$router->get('/patients/create', [PatientController::class, 'create']);
$router->post('/patients', [PatientController::class, 'store']);
$router->get('/patients/{id}/activar', [PatientController::class, 'activate']);
$router->get('/patients/{id}/desactivar', [PatientController::class, 'deactivate']);
$router->get('/patients/{id}/consents/create', [PatientConsentController::class, 'create']);
$router->post('/patients/{id}/consents', [PatientConsentController::class, 'store']);
$router->get('/patients/{id}/consents/{consentId}/activar', [PatientConsentController::class, 'activate']);
$router->get('/patients/{id}/consents/{consentId}/desactivar', [PatientConsentController::class, 'deactivate']);
$router->get('/patients/{id}/instrumentos/create', [PsychometricController::class, 'create']);
$router->post('/patients/{id}/instrumentos', [PsychometricController::class, 'store']);
$router->get('/patients/{id}/instrumentos/{instrumentId}/aplicar', [PsychometricController::class, 'apply']);
$router->post('/patients/{id}/instrumentos/{instrumentId}/aplicar', [PsychometricController::class, 'storeApplication']);
$router->get('/patients/{id}/instrumentos/{resultId}/edit', [PsychometricController::class, 'edit']);
$router->post('/patients/{id}/instrumentos/{resultId}/actualizar', [PsychometricController::class, 'update']);
$router->get('/patients/{id}/instrumentos/{resultId}/activar', [PsychometricController::class, 'activate']);
$router->get('/patients/{id}/instrumentos/{resultId}/desactivar', [PsychometricController::class, 'deactivate']);
$router->get('/patients/{id}/reporte', [ReportController::class, 'show']);
$router->get('/patients/{id}/reporte/exportar', [ReportController::class, 'export']);
$router->get('/patients/{id}/vinculos', [PatientFamilyRelationshipController::class, 'index']);
$router->get('/patients/{id}/vinculos/pdf', [PatientFamilyRelationshipController::class, 'pdf']);
$router->post('/patients/{id}/family-people', [PatientFamilyRelationshipController::class, 'storePerson']);
$router->post('/patients/{id}/family-people/{personId}/desactivar', [PatientFamilyRelationshipController::class, 'deactivatePerson']);
$router->post('/patients/{id}/family-relationships', [PatientFamilyRelationshipController::class, 'store']);
$router->post('/patients/{id}/family-node-position', [PatientFamilyRelationshipController::class, 'position']);
$router->post('/patients/{id}/family-relationships/{relationshipId}/desactivar', [PatientFamilyRelationshipController::class, 'deactivate']);
$router->get('/patients/{id}/family-relationships/{relationshipId}/desactivar', [PatientFamilyRelationshipController::class, 'deactivate']);
$router->post('/patients/{id}/ai-analysis', [AiAnalysisController::class, 'store']);
$router->get('/patients/{id}/ai-history', [AiAnalysisController::class, 'history']);
$router->post('/patients/{id}/ai-analysis/{analysisId}/review', [AiAnalysisController::class, 'review']);
$router->get('/patients/{id}/ai-analysis/{analysisId}/activar', [AiAnalysisController::class, 'activate']);
$router->get('/patients/{id}/ai-analysis/{analysisId}/desactivar', [AiAnalysisController::class, 'deactivate']);
$router->get('/patients/{id}/sessions/{sessionId}/activar', [ClinicalSessionController::class, 'activate']);
$router->get('/patients/{id}/sessions/{sessionId}/desactivar', [ClinicalSessionController::class, 'deactivate']);
$router->get('/patients/{id}', [PatientController::class, 'show']);
$router->get('/patients/{id}/edit', [PatientController::class, 'edit']);
$router->post('/patients/{id}/update', [PatientController::class, 'update']);
$router->get('/patients/{id}/sessions/create', [ClinicalSessionController::class, 'create']);
$router->post('/patients/{id}/sessions', [ClinicalSessionController::class, 'store']);

App::run($router);
